return {
    schema = 1,
    id = "001-basic",
    format = "md",
    source_file = "source.md",
    operations = {
        {
            kind = "highlight",
            text = "unique highlighted phrase",
            occurrence = 1,
            color = "yellow",
        },
        {
            kind = "annotation",
            text = "another sentence that will receive a note",
            occurrence = 1,
            color = "green",
            note = "This annotation was generated by corpusgen.",
        },
        {
            kind = "bookmark",
            anchor = "A final paragraph is used for a bookmark.",
            occurrence = 1,
        },
    },
}
